config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'static_pages/home'

  resources :nominees

  resources :categories

  resources :entries

  root 'static_pages#home'

  get     'leaderboard'   =>  'entries#index'
  get     'login'         =>  'sessions#new'
  post    'login'         =>  'sessions#create'

end

app/models/nominee.rb
class Nominee < ActiveRecord::Base
  has_many :selections, dependent: :destroy
  has_many :entries, through: :selections
  has_many :categories, through: :categories_nominees
  has_many :categories_nominees
end

app/controllers/nominees_controller.rb
class NomineesController < ApplicationController
  before_action :set_nominee, only: [:show, :edit, :update, :destroy]

  # GET /nominees
  # GET /nominees.json
  def index
    @nominees = Nominee.all
    @nominee = Nominee.new
  end

  # GET /nominees/1
  # GET /nominees/1.json
  def show
  end

  # GET /nominees/new
  def new
    @nominee = Nominee.new
  end

  # GET /nominees/1/edit
  def edit
  end

  # POST /nominees
  # POST /nominees.json
  def create
    @nominee = Nominee.new(nominee_params)

    respond_to do |format|
      if @nominee.save
        format.html { redirect_to @nominee, notice: 'Nominee was successfully created.' }
        format.js {}
        format.json { render :show, status: :created, location: @nominee }
      else
        format.html { render :new }
        format.json { render json: @nominee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /nominees/1
  # PATCH/PUT /nominees/1.json
  def update
    respond_to do |format|
      if @nominee.update(nominee_params)
        format.html { redirect_to @nominee, notice: 'Nominee was successfully updated.' }
        format.json { render :show, status: :ok, location: @nominee }
      else
        format.html { render :edit }
        format.json { render json: @nominee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nominees/1
  # DELETE /nominees/1.json
  def destroy
    @nominee.destroy
    respond_to do |format|
      format.html { redirect_to nominees_url, notice: 'Nominee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_nominee
      @nominee = Nominee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def nominee_params
      params.require(:nominee).permit(:name, :category_ids => [])
    end
end

app/helpers/nominees_helper.rb
module NomineesHelper
end

app/views/nominees/_form.html.erb
<%= simple_form_for(@nominee, remote: true) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  	<%= f.input :name %>
  	<%= f.association :categories, as: :check_boxes %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/nominees/_nominee.html.erb
<tr>
  <td><%= nominee.name %></td>
  <td><%= link_to 'Show', nominee %></td>
  <td><%= link_to 'Edit', edit_nominee_path(nominee) %></td>
  <td><%= link_to 'Destroy', nominee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/nominees/create.js.erb
$("<%= escape_javascript(render @nominee) %>").appendTo("#nominees");

app/views/nominees/edit.html.erb
<h1>Editing Nominee</h1>

<%= render 'form' %>

<%= link_to 'Show', @nominee %> |
<%= link_to 'Back', nominees_path %>

app/views/nominees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Nominees</h1>

<%= render 'form' %>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody id="nominees">
  <%= render @nominees %>
  </tbody>
</table>

<br>

<%= link_to 'New Nominee', new_nominee_path %>

app/views/nominees/new.html.erb
<h1>New Nominee</h1>

<%= render 'form' %>

<%= link_to 'Back', nominees_path %>

app/views/nominees/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_nominee_path(@nominee) %> |
<%= link_to 'Back', nominees_path %>