config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'static_pages/home'

  resources :nominees

  resources :categories

  resources :entries

  root 'static_pages#home'

  get     'leaderboard'   =>  'entries#index'
  get     'login'         =>  'sessions#new'
  post    'login'         =>  'sessions#create'

end

app/models/entry.rb
class Entry < ActiveRecord::Base
  has_many :categories, through: :selections
  has_many :nominees, through: :selections
  has_many :selections, dependent: :destroy
  accepts_nested_attributes_for :selections, reject_if: :all_blank

  #returns true if anser matches master
  def correct_answer?(category)
    unless @master.selections.find_by(category: category).nil? || @master.selections.find_by(category: category).nominee.nil?
      self.selections.find_by(category: category).nominee == @master.selections.find_by(category: category).nominee
    else
      return false
    end
  end

  def reset_score
    self.score = 0
  end

  def add_to_score(category)
    self.score += category.value
  end

  def update_score
    @master = Entry.find_by(master: true)
    reset_score
    unless @master.nil?
      self.categories.each do |category|
        if correct_answer?(category)
          add_to_score(category)
        end
      end
      self.save
    end
  end

  def previously_selected?(category, nominee)
    if self.selections.find_by(category_id: category.id)
      self.selections.find_by(category_id: category.id).nominee == nominee
    else
      false
    end
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: [:show, :edit, :update, :destroy]
  before_action :set_categories, only: [:new, :edit]
  after_action :update_scores, only: [:create, :show, :update, :index]

  # GET /entries
  # GET /entries.json
  def index
    @entries = Entry.order(score: :desc)
  end

  # GET /entries/1
  # GET /entries/1.json
  def show
  end

  # GET /entries/new
  def new
    @cat_length = @categories.length
    @entry = Entry.new
    @cat_length.times do |c|
      @entry.selections.new
    end
  end

  # GET /entries/1/edit
  def edit
    @entry = Entry.find(params[:id])
  end

  # POST /entries
  # POST /entries.json
  def create
    @entry = Entry.new(entry_params)

    respond_to do |format|
      if @entry.save
        forget_prev_entries
        remember(@entry)
        format.html { redirect_to @entry, notice: 'Entry was successfully created.' }
        format.json { render :show, status: :created, location: @entry }
      else
        format.html { render :new }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entries/1
  # PATCH/PUT /entries/1.json
  def update
    respond_to do |format|
      if @entry.update(entry_params)          
          format.html { redirect_to @entry, notice: 'Entry was successfully updated.' }
          format.json { render :show, status: :ok, location: @entry }
      else
        format.html { render :edit }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1
  # DELETE /entries/1.json
  def destroy
    @entry.destroy
    respond_to do |format|
      format.html { redirect_to entries_url, notice: 'Entry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entry
      @entry = Entry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def entry_params
      params.require(:entry).permit(:name, selections_attributes: [ :id, :category_id, :nominee_id ])
    end

    def set_categories
      @categories = Category.all
    end

    def update_scores
      @entries = Entry.all
      @entries.each { |entry| entry.update_score }
    end
end

app/helpers/entries_helper.rb
module EntriesHelper

  def master_entry
    @master = Entry.find_by(master: true)
  end

  def total_possible
    if master_entry
      master_entry.score
    else
      return 0
    end
  end

  def show_started?
    start_time = Time.zone.local(2015, 2, 22, 18, 30)
    Time.zone.now > start_time
  end
end

app/views/entries/_form.html.erb
<%= simple_form_for(@entry) do |f| %>
  <% if @entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

      <ul>
      <% @entry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="row">
  <div class="actions">
    <%= f.input :name %>
      <% @i = 0 %>
      <%= f.simple_fields_for :selections do |s| %>
        <% @i += 1 %>
        <% category = Category.find(@i) %>
          <div class="large-4 columns">
          <div class="panel equalHeight">
            <h3><%= category.name %></h3>
            <h5 class="value"><%= pluralize(category.value, 'point') %></h5>
            <%= s.hidden_field :category_id, value: category.id %>
            <% category.nominees.each do |nominee| %>
              <div class="nominee">
                <%= s.radio_button :nominee_id, nominee.id, checked: @entry.previously_selected?(category, nominee) %>
                <%= s.label :nominee_id, nominee.name, value: "#{nominee.id}"  %>
              </div>
            <% end %>
            </div>
          </div>
      <% end %>
    <%= f.button :submit %>
  </div>
</div>
<% end %>

app/views/entries/edit.html.erb
<h1>Edit My Entry</h1>

<%= render 'form' %>

<%= link_to 'Show', @entry %> |
<%= link_to 'Back', entries_path %>

app/views/entries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Leaderboard</h1>
    <% @i = 0 %>
    <% @entries.each do |entry| %>
      <% unless entry.master? %>
        <% @i += 1 %>
        <div class="row leaderboard-row">
          <div class="large-8 small-8 columns"><%= link_to "#{@i}.\s#{entry.name}", entry %>
            <% if current_entry && current_entry.master? %>
              <span><%= link_to 'Delete Entry', entry, method: :delete, data: { confirm: 'Are you sure?' } %></span>
            <% end %>
          </div>
          <div class="large-4 small-4 columns"><%= "#{number_with_precision(entry.score, :precision => 0)} / #{number_with_precision(total_possible, :precision => 0)}" %></div>
        </div>
      <% end %>
    <% end %>

<br>

app/views/entries/new.html.erb
<h1>New Entry</h1>

<%= render 'form' %>

<%= link_to 'Back', entries_path %>

app/views/entries/show.html.erb
<div class="entry-header">
	<h4><%= "#{@entry.name}'s Entry" %></h4>
	<h1>Score: <%= "#{number_with_precision(@entry.score, :precision => 0)} / #{number_with_precision(total_possible, :precision => 0)}" %> </h1>

	<!-- <h1><%= show_started? %></h1>
	 -->
	<% unless show_started? %>
		<% if submitted_entry? && @entry == current_entry %>
			<%= link_to 'Edit This Entry', edit_entry_path(@entry), class: "button" %>
			<div class="countdown-entry">
				<span id = "countdown-edit-text">You may edit your entry for another </span><span class="countdown"></span>
			</div>

			<div class="empty-entry-warning">
				<% @entry.selections.each do |selection| %>
					<% if selection.nominee.nil? %>
						<% @any_empty = true %>
					<% end %>
				<% end %>
				<% if @any_empty %>
					<h3 class="warning">Warning! You haven't filled out all of the categories.  See below.</h3>
				<% end %>
			</div>
		<% end %>
	<% end %>
</div>

<% if @entry == current_entry || show_started? %>
	<div class="row">
		<% @entry.selections.each do |selection| %>
		  <div class="large-4 columns">
		  <% if selection.nominee.nil? %>
			  <div class="panel equalHeight not-selected">
		  <% else %>
			  <div class="panel equalHeight">
		  <% end %>
					<h3><%= selection.category.name %></h3>
	        <h5 class="value"><%= pluralize(selection.category.value, 'point') %></h5>
					<% @cat = Category.find(selection.category.id) %>
					<% @cat.nominees.each do |nominee| %>
						<% if master_entry %>
								<% @master = master_entry.selections.find_by(category_id: @cat) %>
						<% end %>
						<% if nominee == selection.nominee %>
							<% if @master && @master.nominee && nominee == @master.nominee %>
								<div class="nominee selectee correct">
									<%= nominee.name %>
								</div>
							<% elsif @master && @master.nominee %>
								<div class="nominee selectee incorrect">
									<%= nominee.name %>
								</div>
							<% else %>
								<div class="nominee selectee">
									<%= nominee.name %>
								</div>
							<% end %>
						<% elsif @master && @master.nominee && nominee == @master.nominee%>
								<div class="nominee correct">
									<%= nominee.name %>
								</div>					
						<% else %>
							<div class="nominee">
								<%= nominee.name %>
							</div>
						<% end %>
					<% end %>
				</div>
			</div>
		<% end %>
	</div>
<% else %>
	<h2>Entry is hidden until the show starts.</h2>
<% end %>