config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'static_pages/home'

  resources :nominees

  resources :categories

  resources :entries

  root 'static_pages#home'

  get     'leaderboard'   =>  'entries#index'
  get     'login'         =>  'sessions#new'
  post    'login'         =>  'sessions#create'

end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Zurb Foundation %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div data-alert class="alert-box <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
      <%= content_tag :div, msg %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Zurb Foundation 5 %>
<nav class="top-bar" data-topbar role="navigation">
  <ul class="title-area">
  	<li class="name"></li>
    <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
  </ul>
  <div class="top-bar-section">
    <ul class="left">
      <%= render 'layouts/navigation_links' %>
    </ul>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% unless show_started? %>
	<li class="name"><%= link_to 'New Entry', new_entry_path %></li>
<% end %>
<li class="name"><%= link_to 'Log in Entry', login_path %></li>
<li class="name"><%= link_to 'Leaderboard', leaderboard_path %></li>
<% if submitted_entry? %>
	<li class="name"><%= link_to "My Entry", entry_path(current_entry)%></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Oscarsapp" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Oscarsapp" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%# Modernizr is required for Zurb Foundation %>
    <%= javascript_include_tag 'vendor/modernizr' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag '//use.typekit.net/dsb2syi.js' %>
    <script>try{Typekit.load();}catch(e){}</script>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>